# Generated by Django 4.1.7 on 2024-03-03 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('login', models.SlugField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ManyToManyField(related_name='editionright', through='shopping_list.EditingUser', to='shopping_list.normaluser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('product_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='editinguser',
            name='NormalUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.normaluser'),
        ),
        migrations.AddField(
            model_name='editinguser',
            name='shoppingList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist'),
        ),
    ]
