# Generated by Django 4.1.7 on 2024-03-06 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteAccepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('invitehash', models.CharField(default='aaaa', max_length=100, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normaluser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ManyToManyField(related_name='editionright', through='shopping_list.EditingUser', to='shopping_list.normaluser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('product_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listproducts', to='shopping_list.shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='editinguser',
            name='normalUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.normaluser'),
        ),
        migrations.AddField(
            model_name='editinguser',
            name='shoppingList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist'),
        ),
    ]
