# Generated by Django 4.1.7 on 2024-03-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editinguser',
            old_name='NormalUser',
            new_name='normalUser',
        ),
    ]
