# Generated by Django 4.1.7 on 2024-03-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_rename_normaluser_editinguser_normaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listproducts', to='shopping_list.shoppinglist'),
        ),
    ]
