# Generated by Django 4.1.7 on 2024-03-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_normaluser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='editor',
            field=models.ManyToManyField(related_name='shoppinglist', through='shopping_list.EditingUser', to='shopping_list.normaluser'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedshopinglists', to='shopping_list.normaluser'),
        ),
    ]
