# Generated by Django 4.1.7 on 2024-03-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_product_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='editinguser',
            name='inviteAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='invitehash',
            field=models.CharField(default='aaaa', max_length=100, unique=True),
        ),
    ]
