# Generated by Django 4.1.7 on 2024-03-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_shoppinglist_editor_alter_shoppinglist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='email_change_new_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='email_change_url',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='email_change_url_valid_to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
