# Generated by Django 4.1.7 on 2024-03-08 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_normaluser_email_change_new_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='email_change_url_valid_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
